### ISSUE TITLE
Failed to minify format.js

### ISSUE THREAD

**Issue by jd-carroll** [winstonjs/logform#33]
I am working on a React.js project and trying to use Winston@3.0.0 within this project.  I followed the comments outlined here: 

**When I go to run our build using webpack, I see the following error:**
```
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.7.1 and D:\dev\my-project\our-ui\tsconfig.json
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/logform/format.js:7

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
**At first I tried changing the custom error object from ES6 classes to the old fashioned way:**
```javascript
function InvalidFormatError(formatFn) {
  var instance = new Error(`Format functions must be synchronous taking a two arguments: (info, opts)
Found: ${formatFn.toString().split('\n')[0]}\n`);
  Object.setPrototypeOf(instance, Object.getPrototypeOf(this));
  if (Error.captureStackTrace) {
    Error.captureStackTrace(instance, InvalidFormatError);
  }
  return instance;
}

InvalidFormatError.prototype = Object.create(Error.prototype, {
  constructor: {
    value: Error,
    enumerable: false,
    writable: true,
    configurable: true
  }
});

if (Object.setPrototypeOf){
  Object.setPrototypeOf(InvalidFormatError, Error);
} else {
  InvalidFormatError.__proto__ = Error;
}
```

**But that still produced the same errror:**
```
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
ts-loader: Using typescript@2.7.1 and D:\dev\my-project\our-ui\tsconfig.json
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/logform/format.js:7

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Any help is appreciated, not sure if this is a logform issue our a webpack config issue.**

**Comment by indexzero** [comment]
Could you please include all of the relevant configuration you're providing to `webpack`?

**Comment by DABH** [comment]
@ChrisAlderson @indexzero what are your thoughts on shipping pre-transpiled-to-ES5 files for the libraries, e.g. in a `dist` folder?  Makes our lives slightly more complicated (adds a build step, for instance, though CI could automate that) but as the above notes, it's probably a big help for e.g. browser compatibility.

**Comment by chrisahardie** [comment]
I'd certainly appreciate it, I'm loathe to eject from my CRA but would love to integrate Winston!

Thanks for your efforts, this is a great library!

**Comment by justindesrosiers** [comment]
My team would also greatly appreciate the pre transpiled to ES5 files. We ran into this issue yesterday and were left scratching our heads for a few hours until I came across this issue. @revik 's solution has done the trick for us and we will keep an eye on this package if in the future it is shipped with the ES5 files at which point we will remove the rule.

**Comment by mfrisbey** [comment]
@DABH @ChrisAlderson @indexzero I recently had to precompile a module I was working on, so I spent a little time and configured this module to precompile as well. You can see the result at https://github.com/mfrisbey/logform/tree/publish-precompiled. I'd be happy to contribute these changes as a pull request, but since it's fairly invasive I thought I'd run it by you first. All the tests are passing.

I had to make similar changes to [`winston`](https://github.com/mfrisbey/winston/tree/publish-precompiled) and [`winston-transport`](https://github.com/mfrisbey/winston-transport/tree/publish-precompiled), so those changes would also need to be contributed in order for winston to work in a browser setting (in my case, a React app).

**NOTE**
For those wanting to consume winston from a browser, the `File` transport won't work. For security reasons, `fs` functionality is unavailable in the context of a browser. I verified that `Console` works but I haven't tried any of the others.

**What do these modifications do?**
On publish, precompiles all javascript files into a `build` directory, which is included in the final package. Non-compiled javascript source is excluded from the package.

**What Changed?**
* Introduced dev dependencies to:
  * Babel (does the work of precompiling)
  * Rimraf (removes the `build` directory on precompile)
* Changed the package's main file to `build/index.js`
* Moved all javascript files from root directory to a `src` folder
* Updated tests to reference files in `src` folder instead of root

**What will it break?**
Since the source files were moved to a different directory, any `require`s to paths in the module will break (i.e. `require('logform/json');`). I changed one such occurrence in the `winston` module, so that pull request would also need to be merged before moving forward.

Feel free to reach out to me if you have questions or would like to discuss anything further. Thanks!

**Comment by DABH** [comment]
Hi @mfrisbey , thanks for the thorough comment and your work on this!

Indeed, the File transport doesn't work in the browser for the reasons you mentioned.  Others like Console, various HTTP-based transports (post your logs to a server), etc. should work.

I think this change is essentially a requirement to achieve first-class browser support for winston, which is a (the main?) goal for 3.1.  Browsers need ES5 for the foreseeable future.

I'd like @indexzero to +1 this before merging since it is a significant change, but I'm confident enough to say that you should open the PRs for these on all 3 repos.  If we don't hear anything from @indexzero then I will probably merge these, but ideally we'll get consensus from at least one other maintainer :)  Thanks again for taking the initiative on this, it's appreciated!

**Comment by drmmr763** [comment]
Having this same issue trying to run build for browser app with Create React App as my platform. Would love to see these solutions merged so I can avoid doing an eject if possible.

**Comment by sulmanen** [comment]
I used babel.config.js and 

 rules: [
      {
        test: /\.js$/,
        use: {
          loader: "babel-loader",
          options: {
            configFile: path.resolve(__dirname, 'babel.config.js')
          }
        },
        include: [
          path.resolve(__dirname, 'app'),
          path.resolve(__dirname, 'node_modules/logform'),
        ]
      }
    ]
