### ISSUE TITLE
Document the built-in formats

### ISSUE THREAD

**Issue by mmorearty** [winstonjs/logform#9]
It would be very helpful for newcomers if the README contained a list of the built-in formats, with a brief example of the output of each. Currently, it seems you have to dig through the source to figure out what built-in formats are available, and try them in code in order to see what they will look like.

**Comment by indexzero** [comment]
If you're looking for a way to get involved or help the `winston` project a PR for some (or all) of these docs would be most welcome 😺

**Comment by DABH** [comment]
Related to #48, if we document all the built-in formats, we should also aim to provide exact typings for each of the built-in formatters' options -- that way the Typescript definitions sort of self-document the code.  Helps is welcome on these tasks, otherwise we will plan to get to this in an upcoming release!

**Comment by SerayaEryn** [comment]
I'll open a PR to document the built-in formats.

**Comment by DABH** [comment]
I think thanks to the great work in #56 and #64 we can close this now.  For any more documentation requests feel free to open a new issue, or even better a PR!
